### PR TITLE
Correct sha1sums

### PR DESCRIPTION
**Pull request by TheLastGimbus**
Hi!
Was trying to build myself and got

```bash
FAILED: 
In file included from tools/tradefederation/prebuilts/test_harness/Android.mk:55:
vendor/google/sunfish/Android.mk:9: error: vendor/google/sunfish/radio/abl.img SHA1 mismatch (a7f3c4c236b182a5e8cd6af890a17127f669920c != c9c3b0a8ad0d1ba9da52
08bd68e98ec790e48341).
00:11:13 ckati failed with: exit status 1
```

So I ran `device/google/sunfish/setup-makefiles.sh` and got correct sums

Is this script supposed to be run before building? Shouldn't this be in a build pipeline or something? Idk, anyway here are correct ones :tada:

### CODE REVIEW

**Comment by TheLastGimbus** [comment]
Btw i think the same thing is on the `lineage-20` last time i ran it so it would be nice to merge it there too

**Comment by luk1337** [comment]
The checksums are correct. If you compiled after regenerating them on your end, do not flash your build, since it'll brick your phone!

**Comment by TheLastGimbus** [comment]
Huh okay, good to know why that happened to my last Pixel :DDD

However, can you double check? How do I explain this (fresh downloaded zip from here):

```bash
~/dev/android/linago-build ·························································································································· 23:34:18
❯ 7z x proprietary_vendor_google_sunfish-lineage-21.zip 

7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 338401799 bytes (323 MiB)

Extracting archive: proprietary_vendor_google_sunfish-lineage-21.zip
--
Path = proprietary_vendor_google_sunfish-lineage-21.zip
Type = zip
Physical Size = 338401799
Comment = 1413bb424042cc72d67948259603efc24ee63ab0

Everything is Ok                                                               

Folders: 334
Files: 1868
Size:       734524577
Compressed: 338401799
~/dev/android/linago-build ······················································································································ 32s 23:34:55
❯ cat proprietary_vendor_google_sunfish-lineage-21/Android.mk 
# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sunfish/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sunfish)

$(call add-radio-file-sha1-checked,radio/abl.img,c9c3b0a8ad0d1ba9da5208bd68e98ec790e48341)
$(call add-radio-file-sha1-checked,radio/aop.img,3e90992daa4dccbf2f7c3fd96316772210eadbfe)
$(call add-radio-file-sha1-checked,radio/devcfg.img,9f815d4a5ca3c2478370fb8fdaf76610547a5d96)
$(call add-radio-file-sha1-checked,radio/hyp.img,8fd4bc1d9250281bf72bbf2811fa45c1eeb60dc1)
$(call add-radio-file-sha1-checked,radio/keymaster.img,47dbb68438d7247c620a6031acfb6e5e1434da38)
$(call add-radio-file-sha1-checked,radio/modem.img,f02c5986274cffc348cdf6b91c1bad26583441e6)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3277904e619487d05b385043099e83ccc828aa30)
$(call add-radio-file-sha1-checked,radio/tz.img,4079e9ea93ffc87bc62147a8164f878b73cf3684)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,f2736dea540e99cc940caef51cf2b988705c6d32)
$(call add-radio-file-sha1-checked,radio/xbl.img,87569e5bb09bcced45a8c6a37e61a47506f550a2)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,880d77daa41ac9d7fa93553759e339e4f062a206)

endif
~/dev/android/linago-build ·························································································································· 23:35:08
❯ cd proprietary_vendor_google_sunfish-lineage-21/radio/
~/dev/android/linago-build/proprietary_vendor_google_sunfish-lineage-21/radio ······································································· 23:35:25
❯ sha1sum abl.img aop.img devcfg.img hyp.img keymaster.img modem.img qupfw.img tz.img uefisecapp.img xbl.img xbl_config.img
a7f3c4c236b182a5e8cd6af890a17127f669920c  abl.img
23d06fdd19c8e7e12bf6c0a2ca11c86540a75ec4  aop.img
fc75e15e80d05fd97e5485e61e2266076325c710  devcfg.img
5b135120df96c2ba9d1da67d49f5b4b5dac1c1fa  hyp.img
e55b41dc4dfce9567d8cb3e0f4febcf8834cbeb3  keymaster.img
61d087b16514a71ab0c8d5fe1982de59787534d8  modem.img
6bdf862507aa4e75bcbae1a21f815561ccd9a20c  qupfw.img
208389bd45ee744daf9bbfb11879416e9cfbbb37  tz.img
0a388e724e31b2aa0b52426c5e947bd0e88b7487  uefisecapp.img
a44b3e84943ff13d833ba2768fb9497d094726bb  xbl.img
e73e5b4ea9734153bab52143cb1b8f16652b2b8e  xbl_config.img
~/dev/android/linago-build/proprietary_vendor_google_sunfish-lineage-21/radio ······································································· 23:35:26
❯ 
```

**Comment by haggertk** [comment]
These repos are not meant to be used as downloaded zips, but as true git repos, ideally listed in a local_manifest so that repo appropriately keeps them in sync with the rest of the tree.

The specific files in question aren't the radio images themselves, but LFS pointers. They contain a checksum and size of the complete file download (look at them in github). If the repo is init-ed correctly and git-lfs is properly installed by your distro package then a repo sync will take care of everything for you, if not then you need to manually `git lfs pull` in this project's directory when you get a build error.

**Comment by TheLastGimbus** [comment]
Ah, that was a very instructive brick :skull_and_crossbones: thanks for claryfication!

And, long-standing big big thanks for maintaing *all* of this, by the way. Every time I turn on flashlight by long pressing power button, i think "huh, that's thanks to some awesome people that maintain all of this". Great job!

**Pull request closed without merging**
